version: "3.3"
services:
    
    nginx:
        image: nginx:stable-alpine
        ports: 
            - 80:80
        volumes:
            - ./nginx/default.conf:/etc/nginx/conf.d/default.conf

    mysql:
        image: mysql:latest
        restart: always
        environment:
            MYSQL_DATABASE: wp
            MYSQL_USER: wp
            MYSQL_PASSWORD: secret
            MYSQL_ROOT_PASSWORD: secret

    php:
        build:
           context: .
           dockerfile: php.dockerfile 

    wordpress:
        image: wordpress:latest
        restart: always
        ports:
            - 8080:80
            - 443:443
        environment:
            WORDPRESS_DB_HOST: mysql
            WORDPRESS_DB_USER: wp
            WORDPRESS_DB_PASSWORD: secret
            WORDPRESS_DB_NAME: wp
        # volumes:
        #     - ./html:/var/www/html
